name: TowerLog
options:
  bundleIdPrefix: studio.mikegyver
settings:
  base:
    SWIFT_VERSION: '5.0'
    IPHONEOS_DEPLOYMENT_TARGET: '17.0'
    TARGETED_DEVICE_FAMILY: '1'
    MARKETING_VERSION: '1.0.2'
    CURRENT_PROJECT_VERSION: '3'
targets:
  TowerLog:
    type: application
    platform: iOS
    sources:
      - path: TowerLog
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: studio.mikegyver.towerlog
        INFOPLIST_FILE: TowerLog/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: '1,2'
        CODE_SIGN_STYLE: Automatic
